apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-laht
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-laht
    app.kubernetes.io/part-of: ci1t-830-0017-app
  name: devfile-sample-laht
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-laht
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-laht
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0017-tenant/ci1t-830-0017-app/devfile-sample-laht@sha256:75d9f8c9790c091374e1651a42c6109db5bd6601aa0e0f09be87a1fdd9243116
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
